server:
  port: 9090

spring:
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/end_to_end_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: mail.gmx.net # smtp.gmail.com
    port: 587          # 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true