#Debug
logging:
  level:
    edu.yacoubi.usermanagement.config.CustomUserDetailsService: DEBUG
    edu.yacoubi.usermanagement: INFO

#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD:
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: end_to_end_db


#Server
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: mail.gmx.net    # smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ${EMAIL}          # Environment variable
EMAIL_PASSWORD: ${PASSWORD} # Environment variable
VERIFY_EMAIL_HOST: http://localhost:9090
#CONTROLLER_PATH:  /api/v1/user/verify/account?token=
#CONTROLLER_PATH:  /registration/verifyEmail?token=