server:
  port: 8080
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    initialization-mode: always
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
        globally_quoted_identifiers: true
        format_sql: true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mine:
          charset: UTF
        smtp:
          writetimeout: 1000
          connectiontimeout: 1000
          timeout: 1000
          auth: true
          starttls:
            enable: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
  sql:
    init:
      mode:  never # ALWAYS, EMBEDDED, NEVER
      continue-on-error: false
      schema-location: classpath:/data/schema.sql
      data-location: classpath:/data/data.sql
#  servlet:
#    multipart:
#      enable: true
#      max-file-size: 1000MB
#      max-request-size: 1000MB