#Debug
logging:
  level:
    edu.yacoubi.usermanagement.config.CustomUserDetailsService: DEBUG
    edu.yacoubi.usermanagement: INFO

#Database
POSTGRES_USERNAME: ${ENV_POSTGRES_USERNAME}
POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: confirmationdb


#Server
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: mail.gmx.net    # smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ${EMAIL}          # Environment variable
EMAIL_PASSWORD: ${PASSWORD} # Environment variable
VERIFY_EMAIL_HOST: http://localhost:9090
#CONTROLLER_PATH:  /api/v1/user/verify/account?token=
#CONTROLLER_PATH:  /registration/verifyEmail?token=